export const ROUTER_URL = {
  USER_PAGE: "/user",
  ROLE_PAGE: "/role",
  PERMISSION_PAGE: "/permission",
  FORM_PAGE: "/form",
  FORM_VERSION_PAGE: "/form-version",
  FORM_GROUP_PAGE: "/form-group",
  FORM_FIELD_PAGE: "/form-field",
  LOGIN_PAGE: "/login",
  DASHBOARD_PAGE: "/",
  PROFILE_PAGE: "/profile",
  SETTING_PAGE: "/settings",
  FORM_BUILDER_PAGE: "/form-builder/:form_id",
  NOT_FOUND_PAGE: "*",
};

export const PAGE_NAME = {
  USER: "Quản lý người dùng",
  ROLE: "Quản lý người vai trò",
  PERMISSION: "Quản lý người quyền hạn",
  FORM: "Quản lý biểu mẫu",
  FORM_VERSION: "Quản lý phiên bản biểu mẫu",
  FORM_GROUP: "Quản lý nhóm biểu mẫu",
  FORM_FIELD: "Quản lý trường biểu mẫu",
  LOGIN: "Trang đăng nhập",
  DASHBOARD: "Trang Dashboard",
  PROFILE: "Trang hồ sơ",
  SETTING: "Trang cài đặt",
  NOT_FOUND: "Không tìm thấy trang",
  NOT_PERMISSION: "Không có quyền truy cập",
  FORM_BUILDER: "Xây dựng biểu mẫu",
};
