export const ROUTER_URL = {
  USER_PAGE: "/user",
  ROLE_PAGE: "/role",
  PERMISSION_PAGE: "/permission",
  FORM_PAGE: "/form",
  LOGIN_PAGE: "/login",
  DASHBOARD_PAGE: "/",
  PROFILE_PAGE: "/profile",
  SETTING_PAGE: "/settings",
  FORM_BUILDER_PAGE: (form_id: string) => {
    return `/form-builder/${form_id}`;
  },
  FORM_BUILDER_PREVIEW_PAGE: `viewForm`,
  FORM_BUILDER_RESPONSE_PAGE: `response`,
  FORM_BUILDER_STATISTICS_PAGE: `statistics`,
  FORM_BUILDER_MAIL_HISTORY_PAGE: `mail-history`,
  FORM_BUILDER_SCORING_SECTION_SCHOLARSHIP_PAGE: `scoring-section-scholarship`,
  FORM_BUILDER_ASSIGEMENT_SCHOLARSHIP_PAGE: `assignment-scholarship`,
  FORM_BUILDER_SCORING_RESPONSE_PAGE: `detail-scoring-response`,
  FORM_BUILDER_FILTER_RESPONSE_PAGE: `filter-response`,
  NOT_FOUND_PAGE: "*",
  UNIVERSITY_PAGE: "/university",
  REVIEW_APPLICATION_PAGE: "/review-application",
  DETAIL_REVIEW_APPLICATION_PAGE: (assignment_id: string) => {
    return `/review_form_response_assigned/${assignment_id}`;
  },
  HISTORY_RVIEW_APPLICATION_PAGE: "/review-history",
};

export const PAGE_NAME = {
  USER: "Quản lý người dùng",
  ROLE: "Quản lý người vai trò",
  PERMISSION: "Quản lý người quyền hạn",
  FORM: "Quản lý biểu mẫu",
  LOGIN: "Trang đăng nhập",
  DASHBOARD: "Trang Dashboard",
  PROFILE: "Trang hồ sơ",
  SETTING: "Trang cài đặt",
  NOT_FOUND: "Không tìm thấy trang",
  NOT_PERMISSION: "Không có quyền truy cập",
  FORM_BUILDER: "Thiết kế",
  FORM_BUILDER_PREVIEW: "Xem trước",
  FORM_BUILDER_RESPONSE: "Hồ sơ đã nhận",
  FORM_BUILDER_STATISTICS: "Thống kê",
  FORM_BUILDER_MAIL_HISTORY: "Lịch sử gửi mail",
  FORM_BUILDER_SCORING_SECTION_SCHOLARSHIP: "Phần điểm biểu mẫu",
  FORM_BUILDER_ASSIGEMENT_SCHOLARSHIP: "Phân công hồ sơ",
  FORM_BUILDER_SCORING_RESPONSE: "Chi tiết điểm hồ sơ",
  FORM_BUILDER_FILTER_RESPONSE: "Lọc hồ sơ",
  UNIVERSITY: "Quản lý trường học",
  REVIEW_APPLICATION: "Hồ sơ được phân công",
  DETAIL_REVIEW_APPLICATION: "Chấm điểm hồ sơ",
  REVIEW_HISTORY: "Lịch sử chấm điểm",
};
